// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('Not configured for macOS');
      case TargetPlatform.windows:
        throw UnsupportedError('Not configured for windows');
      case TargetPlatform.linux:
        throw UnsupportedError('Not configured for linux');
      default:
        throw UnsupportedError('Not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalsF59zp7uk6dgkl22M6GTZIvPeq7MOw',
    appId: '1:270955863018:web:09b82430dbc3294fd8b093',
    messagingSenderId: '270955863018',
    projectId: 'edulearn-8f249',
    storageBucket: 'edulearn-8f249.firebasestorage.app',
    authDomain: 'edulearn-8f249.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCalsF59zp7uk6dgkl22M6GTZIvPeq7MOw',
    appId: '1:270955863018:android:be2f560b1bfc39fed8b093',
    messagingSenderId: '270955863018',
    projectId: 'edulearn-8f249',
    storageBucket: 'edulearn-8f249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7lCt815uHIfsqMXsSDdF3W22pMpBcMik',
    appId: '1:270955863018:ios:43ec34ed6f99160bd8b093',
    messagingSenderId: '270955863018',
    projectId: 'edulearn-8f249',
    storageBucket: 'edulearn-8f249.firebasestorage.app',
    iosClientId: '270955863018-p7ih2vpptni9tkqrhcf0mshes121v5ss.apps.googleusercontent.com',
    iosBundleId: 'com.edulearn.app.edulearn',
  );
}